-- Enable useful extensions
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Grant full privileges
GRANT ALL PRIVILEGES ON DATABASE keepup TO keepup;
GRANT ALL PRIVILEGES ON SCHEMA public TO keepup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO keepup;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO keepup;
